### ISSUE TITLE
所以只给题 不给答案的嘛 哈哈哈哈哈

### ISSUE THREAD

**Issue by bd67625** [resumejob/interview-questions#1]
如题

**Comment by Windsooon** [comment]
1. 仓库中列出的面试问题在搜索引擎都能找到大量的参考资料，大家在搜索答案的过程或许会对问题本身有更深的了解并且能够培养分辨正确答案的能力。
2. 如果提供答案的话，可能会造成背答案的情况出现，而在面试过程中背答案是非常容易被辨别出来以及降低评价的。
